### ISSUE TITLE
Incompatible PHP version 7.1.23

### ISSUE THREAD

**Issue by Andeweg86** [ICEPAY/Magento-2#11]
Hi, 

While installing the ICEPAY module for magento 2 it throws an exception about an incompatible PHP version, can you tell me the roadmap when this version (7.1.23) is supported?

  [InvalidArgumentException]
  Package icepay/icepay-magento2-module at version dev-master has a PHP requirement incompatible with your PHP version (7.1.23)

With kind regards,
Marcel

**Comment by tsygankov** [comment]
Hi Marcel,

Could you please try installing version 1.2.0 available in the Dev branch? It is now in Release Candidate state.

**Comment by Andeweg86** [comment]
Hi tsygankov,

thanks for the quick response! It works like a charm!
