### ISSUE TITLE
Table 'foo_bar.icepay_icpcore_paymentmethod' doesn't exist

### ISSUE THREAD

**Issue by ReadySteadyFlow** [ICEPAY/Magento-2#2]
Hello! 

I've been trying to get the IcePay module working for some time now. I copied the files, both from the IcePay website and GitHub Dev branch to 'app/code', listed the extension in 'app/etc/config.php' and executed "setup:upgrade" through 'bin/magento'. However, both in the front-end (cart / checkout) and back-end (Sales > Payment Methods), Magento gives me the following error:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'foo_bar.icepay_icpcore_paymentmethod' doesn't exist, query was: SELECT COUNT(*) FROM `icepay_icpcore_paymentmethod` AS `main_table``

Is this a known error? Thank you in advance!

**Comment by tsygankov** [comment]
Hi,

No, we haven't seen this error before. 

Can you please check if DB tables icepay_icpcore_issuer and icepay_icpcore_paymentmethod exist in your database?

If not, can you please execute bin/magento setup:upgrade again and copy-paste the output here?

I suppose that something is wrong with DB table prefix. Do you really use ''foo_bar' as table 
prefix? If not please check in app/code/etc/env.php file if your DB prefix is correct. 

Example. Empty prefix.
![1](https://cloud.githubusercontent.com/assets/15112699/20456096/d2727a3e-ae75-11e6-9ea1-a41f82c6563a.png)

If you have installed Magento 2 with table prefix 'foo_bar' and later removed it, please try to clean and regenerate Magento cache. Probably executing php/magento cache:clean will do the trick.

**Comment by ReadySteadyFlow** [comment]
Thank you for the quick reply!

> Do you really use ''foo_bar' as table 
prefix? If not please check in app/code/etc/env.php file if your DB prefix is correct.

No, this prefix was just an example :) The correct prefix is listed in our `env.php`

> Can you please check if DB tables icepay_icpcore_issuer and icepay_icpcore_paymentmethod exist in your database?

I've checked, and I can't find any reference to Icepay or IcpCore in our database. So that explains the error. This hasn't been a problem when installing other modules. However, I did use composer for other installations. Below you'll find what I did to install your module. Maybe you can see what went wrong.

1. create `Icepay` in `app/code`
2. copy `IcpCore` folder from Github to `Icepay`
3. run `php bin/magento setup:upgrade`
4. run `php bin/magento setup:di:compile` just to be sure

Any idea what went wrong here?

**Comment by tsygankov** [comment]
>  create Icepay in app/code
    copy IcpCore folder from Github to Icepay
    run php bin/magento setup:upgrade
    run php bin/magento setup:di:compile just to be sure

Can you please check if Icepay_IcpCore module is listed in the output of `magento setup:upgrade`?

![2](https://cloud.githubusercontent.com/assets/15112699/20458782/0b23119a-aeb7-11e6-8ab2-0d7352179d8d.png)

I would suggest  to try the following steps:

**Completely uninstall the module**
1. run `bin/magento module:disable Icepay_IcpCore`
2. remove the folder `app/code/Icepay`
3. Execute `DELETE FROM `setup_module` WHERE module = 'Icepay_IcpCore';` in Magento DB
4. Remove DB tables `icepay_icpcore_issuer`and `icepay_icpcore_paymentmethod` (probably they do not exist in your case)
5. Remove the line with `Icepay_IcpCore `from `app/etc/config.php`
6. Run `bin/magento setup:upgrade`
7. Check that Icepay_IcpCore module is not listed
8. Clean Magento cache by executing `bin/magento cache:clean`

Check if Magento 2 works and there are no errors/problems

**Install the ICEPAY module**
1. Navigate to the `app/code` folder
2.1 If you have Git installed execute `git clone -b Dev https://github.com/ICEPAYdev/Magento-2.git Icepay`. NB! If you use Git in production do not forget to restrict access to Git system files.
2.2 If you don't have Git installed download the Dev branch [contents](https://github.com/ICEPAYdev/Magento-2/archive/Dev.zip) to the `app/code` folder, uncompress the archive and rename `Magento-2-Dev` folder to `Icepay`
3. Execute `bin/magento setup:upgrade`
4. Check if Icepay_IcpCore module is listed in the output
5. Execute `bin/magento cache:clean`

Check if the module is working fine. 

Btw, which version of Magento are you using? The module will work with Magento 2.0.x and Magento 2.1.x. Compatibility with Magento 2.2.x (dev) is not tested.

**Comment by tsygankov** [comment]
You can also try just executing 
3. Execute DELETE FROM setup_module WHERE module = 'Icepay_IcpCore'; in Magento DB 

The installer won't run again if it was already executed. Executing the mentioned SQL statement should force it to run again.

**Comment by tsygankov** [comment]
Hi,

Do you have any updates?

**Comment by ReadySteadyFlow** [comment]
Most certainly, your suggestions resolved the issue. Details:

- Icepay_IcpCore was listed in the `magento setup:upgrade` output
- I reinstalled the module multiple times in the past. The only step I never performed was `DELETE FROM setup_module WHERE module = 'Icepay_IcpCore';`
- `Icepay_IcpCore`  was listed in `setup_module`, and deleting it solved the problem. Thank you very much. 

Ps. do you have a estimation/time path for when the module moves out of development into bèta/stable?

**Comment by tsygankov** [comment]
Currently we have 2 bugs that are blocking the release:

- Javascript error when Credit Card payment method is disabled
- Checkout fails when downloadable products are in the cart

Both problems will be fixed this week. If no new problems will be found during the testing phase, we will release a stable version on Saturday.
