### ISSUE TITLE
Errors during compilation

### ISSUE THREAD

**Issue by lerygit** [ICEPAY/Magento-2#3]
Hello,

I installed the v1.0.1-beta1 on Magento 2.1.3 and received the following error when i run setup:di:compile
![schermafbeelding 2017-02-09 om 17 57 18](https://cloud.githubusercontent.com/assets/13809701/22794000/dd0ec79c-eef1-11e6-8f3a-539e8a18e7a5.jpg)

 (Also when i hit the save button i get a 404 as result).

Is this a known error?

**Comment by tsygankov** [comment]
Hi hazenlinssenvof,

Please check the latest version in the master branch, this issues are already fixed, however we haven't released a new version yet.

There is one more issue in the that is not fixed yet - payment method synchronization is not working properly when the scope is website or Default Config. As a result - payment methods are not shown on frontend. As a workaround, please switch to the [Store View](http://docs.magento.com/m2/ce/user_guide/configuration/scope.html) mode and run the synchronization procedure for specific store view. This issue will be fixed very soon. We plan to release a new version of the module on Monday.

**Comment by hazenlinssenvof** [comment]
Thanks for the fix.
Now when we try to inset the links in the customer panel of ICEPAY we get a result like this form the postback url: 
(I setup a temporally test domain where we can test the extension form, this is not the clients real domain!) 

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Order not found

Exception #0 (Magento\Framework\Exception\LocalizedException): Order not found
#0 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Icepay/IcpCore/Controller/Postback/Notification/Interceptor.php(24): Icepay\IcpCore\Controller\Postback\Notification->execute()
#1 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/App/Action/Action.php(102): Icepay\IcpCore\Controller\Postback\Notification\Interceptor->execute()
#2 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Icepay\IcpCore\Controller\Postback\Notification\Interceptor->___callParent('dispatch', Array)
#4 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Icepay\\IcpCore\\...', 'dispatch', Object(Icepay\IcpCore\Controller\Postback\Notification\Interceptor), Array, 'contextPlugin')
#5 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#6 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Icepay\IcpCore\Controller\Postback\Notification\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#7 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Icepay\\IcpCore\\...', 'dispatch', Object(Icepay\IcpCore\Controller\Postback\Notification\Interceptor), Array, 'customer-app-ac...')
#8 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Icepay\IcpCore\Controller\Postback\Notification\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Icepay\\IcpCore\\...', 'dispatch', Object(Icepay\IcpCore\Controller\Postback\Notification\Interceptor), Array, 'storeCheck')
#11 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Icepay\IcpCore\Controller\Postback\Notification\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Icepay\\IcpCore\\...', 'dispatch', Object(Icepay\IcpCore\Controller\Postback\Notification\Interceptor), Array, 'weee-app-action...')
#14 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Icepay\IcpCore\Controller\Postback\Notification\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Icepay\\IcpCore\\...', 'dispatch', Object(Icepay\IcpCore\Controller\Postback\Notification\Interceptor), Array, 'tax-app-action-...')
#17 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Icepay\IcpCore\Controller\Postback\Notification\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Icepay\IcpCore\Controller\Postback\Notification\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Icepay/IcpCore/Controller/Postback/Notification/Interceptor.php(52): Icepay\IcpCore\Controller\Postback\Notification\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/App/FrontController.php(55): Icepay\IcpCore\Controller\Postback\Notification\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#23 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#24 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#27 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#30 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#33 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#38 /var/www/vhosts/lfpdev.hlmarketing.nl/httpdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#39 {main}

**Comment by tsygankov** [comment]
Thanks for the detailed info, I will check the problem in few hours.

**Comment by hazenlinssenvof** [comment]
Thank you! You want the test url to be live?
Otherwise i set it to maintenance mode enable


Voor vragen en/of opmerkingen bel mij gerust!
Met Vriendelijke Groet,

Leroy Linssen

Tel: 		+ 31(0)45 203 1052
Mail: 	info@hlmarketing.nl
Website: 	www.hlmarketing.nl <http://www.hlmarketing.nl/>

**Comment by tsygankov** [comment]
Yes, please, it can help to find the problem.

**Comment by tsygankov** [comment]
Ok, looks like that's a known issue, just we forgot to merge the bugfix to the master branch. I will do it in ~30 min.

**Comment by tsygankov** [comment]
The [bugfix](https://github.com/ICEPAYdev/Magento-2/commit/12c78b2b849d291a2ee6f1a9515a15c285dcb282) is in the master branch now.

Our QA engineers will start testing the latest changes tomorrow (Tuesday). I will make a new release as soon as they will confirm that no blocking problems found.

**Comment by tsygankov** [comment]
At the moment 2 issues found in v1.0.1-beta2, I don't know yet if they are blocking or not.

```
Magento 2: Wrong issuers shown for 09xx service number payment method

Environment: *********
Module version: Magento 2 v1.0.1-beta2

PREREQUISITES:

Payment methods are successfully retrieved in the Default Store View.

STEPS TO REPRODUCE:

    Log in as admin
    Go to Stores -> Configuration -> General
    Click on Single-Store Mode
    Choose "YES" in Enable Single-Store Mode
    Click on Save Config
    Go to Sales -> ICEPAY -> Payment Methods
    Click on Sync and confirm
    Go to front end
    Log in
    Add Test product to cart
    Click on the cart icon
    Click on Go to Checkout
    Click on Next
    Choose 09xx service number

OBSERVED:

The 09xx service number payment method has issuers from iDeal
2017-02-14_16-54-58.png

EXPECTED:

The 09xx service number payment method has its own issuers

```
-----
```

Payment methods list has duplicates after changing to Single Store Mode

Environment: ************
Module version: Magento 2 v1.0.1-beta2

PREREQUISITES:

Payment methods are successfully retrieved in the Default Store View

STEPS TO REPRODUCE:

    Log in as admin
    Go to Stores -> Configuration -> General
    Click on Single-Store Mode
    Choose "YES" in Enable Single-Store Mode
    Click on Save Config
    Go to Sales -> ICEPAY -> Payment Methods
    Click on Sync and confirm

OBSERVED:

Payment methods list contains duplicates (presumably from the Default store view);

EXPECTED:

All Payment methods from the Default store view are replaced with the new ones; no duplicates are shown

```

**Comment by tsygankov** [comment]
The problem should be fixed in the latest version of the module. Please reopen this issue if this is still a problem for you.
